use serde::{Deserialize, Serialize};

// EncryptedEvent represents a single event log in the server.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct EncryptedEvent {
    pub event_id: String,           // Unique event ID generated by the client
    pub server_id: Option<i64>,     // An auto-iterated id generated by the server
    pub account_id: String,         // Account this event belongs to
    pub device_id: String,          // Device that pushed the event
    pub is_snapshot: bool,          // Defines if the log is a snapshot or a common event
    pub encrypted_payload: Vec<u8>, // The actual payload, encrypted by the client
}

// Client to server fetch request
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SyncPullRequest {
    #[serde(default)]
    pub after_server_id: Option<i64>, // Optional cursor position so client doesn't need to get all logs.
}

// Server to client response for fetch request
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SyncPullResponse {
    pub events: Vec<EncryptedEvent>, // Vector of all events for the client (can be empty)
    pub latest_server_id: Option<i64>, // The latest server-made ID. Can be null if server has no logs yet.
}

// Client to server push request
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SyncPushRequest {
    pub new_events: Vec<EncryptedEvent>, // New events sent by the client
}

// Server to client response for push request
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SyncPushResponse {
    // The server confirms exactly which client UUIDs it successfully saved.
    // The client uses this list to safely delete items from its local pending queue.
    pub accepted_event_ids: Vec<String>,

    // The new latest server-made ID after this push for cursor position update
    pub latest_server_id: i64,
}
